import { assistantStyles } from './assistant-styles.js';
import { assistantTemplate } from './assistant-template.js';
import type { AssistantUiState, ConversationMessage, ConversationState, ExtensionPreferences } from '../shared/types.js';

const statusLabel: Record<ConversationMessage['status'], string> = { capturing:'Ouvindo',transcribing:'Transcrevendo',ready:'Pronto para enviar',submitting:'Enviando',queued:'Na fila','generating-video':'Gerando vídeo',completed:'Concluído',failed:'Falhou',cancelled:'Cancelado' };
export class AssistantUi {
  readonly host=document.createElement('div'); readonly shadow:ShadowRoot; private nearBottom=true; private state:AssistantUiState={minimized:false,unreadCount:0,draft:'',activeConversationId:''};
  constructor(private submit:(text:string,id?:string)=>void, private audio:(mode:'microphone'|'tab-audio'|'stop')=>void, private clear:()=>void){this.host.id='neotalk-assistant-host';this.shadow=this.host.attachShadow({mode:'open'});this.shadow.innerHTML=`<style>${assistantStyles}</style>${assistantTemplate}`;document.documentElement.append(this.host);this.bind()}
  private q<T extends Element>(selector:string){return this.shadow.querySelector<T>(selector)!}
  private bind(){const feed=this.q<HTMLElement>('.feed'),textarea=this.q<HTMLTextAreaElement>('textarea');feed.addEventListener('scroll',()=>this.nearBottom=feed.scrollHeight-feed.scrollTop-feed.clientHeight<80);this.q('.send').addEventListener('click',()=>this.sendDraft());textarea.addEventListener('input',()=>{textarea.style.height='auto';textarea.style.height=`${textarea.scrollHeight}px`;this.persist({draft:textarea.value})});textarea.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();this.sendDraft()}});this.q('.minimize').addEventListener('click',()=>this.setMinimized(true));this.q('.launcher').addEventListener('click',()=>this.setMinimized(false));this.q('.menu').addEventListener('click',()=>{const pop=this.q<HTMLElement>('.menu-popover'),button=this.q<HTMLButtonElement>('.menu');pop.hidden=!pop.hidden;button.setAttribute('aria-expanded',String(!pop.hidden))});this.q('.clear').addEventListener('click',()=>this.clear());this.q('.settings').addEventListener('click',()=>chrome.runtime.openOptionsPage());this.q('.tab-audio').addEventListener('click',()=>this.audio('tab-audio'));this.q('.mic').addEventListener('click',()=>this.audio('microphone'));this.shadow.addEventListener('click',e=>{const button=(e.target as Element).closest<HTMLButtonElement>('.retry');if(button)this.submit(button.dataset.text??'',button.dataset.id)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!this.state.minimized)this.setMinimized(true)})}
  private sendDraft(){const textarea=this.q<HTMLTextAreaElement>('textarea'),text=textarea.value.trim();if(!text)return;this.submit(text);textarea.value='';textarea.style.height='auto';this.persist({draft:''})}
  restore(state:AssistantUiState){this.state=state;this.q<HTMLTextAreaElement>('textarea').value=state.draft;this.setMinimized(state.minimized,false)}
  setDraft(text:string){this.q<HTMLTextAreaElement>('textarea').value=text;this.persist({draft:text});this.q<HTMLTextAreaElement>('textarea').focus()}
  render(conversation:ConversationState){const feed=this.q<HTMLElement>('.feed'),wasNear=this.nearBottom;feed.replaceChildren();if(!conversation.messages.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='Sua conversa aparecerá aqui. Escreva, selecione um texto ou use uma fonte de áudio.';feed.append(empty)}conversation.messages.forEach(message=>feed.append(this.message(message)));if(wasNear)feed.scrollTop=feed.scrollHeight;if(this.state.minimized)this.persist({unreadCount:this.state.unreadCount+1});}
  private message(message:ConversationMessage){const item=document.createElement('article');item.className=`message ${message.role}`;const text=document.createElement('p');text.textContent=message.text;item.append(text);if(message.fileUrl){const video=document.createElement('video');video.src=message.fileUrl;video.controls=true;video.playsInline=true;video.setAttribute('aria-label',`Vídeo em Libras para: ${message.text}`);item.append(video)}const detail=document.createElement('small');detail.textContent=message.error||statusLabel[message.status];if(message.error)detail.className='error';item.append(detail);if(message.status==='failed'){const retry=document.createElement('button');retry.className='retry';retry.textContent='Tentar novamente';retry.dataset.id=message.id;retry.dataset.text=message.text;item.append(retry)}return item}
  private setMinimized(value:boolean,persist=true){this.state.minimized=value;this.q<HTMLElement>('.panel').style.display=value?'none':'grid';this.q<HTMLElement>('.launcher').style.display=value?'block':'none';this.q('.launcher').setAttribute('aria-expanded',String(!value));if(!value){this.state.unreadCount=0;this.q<HTMLTextAreaElement>('textarea').focus()}const badge=this.q<HTMLElement>('.badge');badge.hidden=!this.state.unreadCount;badge.textContent=String(this.state.unreadCount);if(persist)this.persist({minimized:value,unreadCount:this.state.unreadCount})}
  private persist(patch:Partial<AssistantUiState>){this.state={...this.state,...patch};void chrome.storage.local.set({neotalkAssistantUi:this.state})}
}
